# Generated by Django 3.2.13 on 2022-08-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('isAdmin', models.BooleanField(default=False, max_length=200)),
                ('genre', models.IntegerField(default=0, max_length=200)),
                ('age', models.IntegerField(default=20, max_length=200)),
                ('like_movies', models.CharField(max_length=200)),
                ('like_age', models.CharField(max_length=200)),
                ('time', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
