# Generated by Django 3.2.13 on 2022-08-10 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsWeb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
    ]
