# Generated by Django 3.2.13 on 2022-08-10 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsWeb', '0003_auto_20220810_0917'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user111',
            new_name='users',
        ),
    ]
