# Generated by Django 3.2.13 on 2022-08-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsWeb', '0004_rename_user111_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('topCast', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=200)),
                ('actor', models.CharField(max_length=200)),
                ('poster', models.CharField(max_length=200)),
                ('date', models.CharField(default='', max_length=200)),
                ('rating', models.CharField(default='', max_length=200)),
                ('time', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
