# Generated by Django 3.2.13 on 2022-08-10 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsWeb', '0006_auto_20220810_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rate',
            new_name='rating',
        ),
    ]
