# Generated by Django 3.2.13 on 2022-08-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsWeb', '0007_rename_rate_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='like_movies_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
