# Generated by Django 3.2.13 on 2022-08-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsWeb', '0012_auto_20220811_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='push',
            name='pusername_like_movies',
            field=models.CharField(default='', max_length=200),
        ),
    ]
