# Generated by Django 3.2.13 on 2022-08-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsWeb', '0013_push_pusername_like_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('pusername', models.CharField(max_length=200)),
                ('time', models.CharField(default='', max_length=200)),
                ('message', models.CharField(default='', max_length=200)),
                ('isRead', models.BooleanField(default=False, max_length=200)),
            ],
        ),
    ]
